# pr1.gql
DataGraph graph = ACCESS("access.n4j")

graph = graph.CASE(:LABEL.HAS("Visitor") OR age << 25)

DataGraph result

THROUGH (Node node : graph) {
    Node filteredNode
    filteredNode.:ID = node.:ID
    filteredNode.age = node.age
    filteredNode.:LABEL = node.:LABEL 
    result.PLUS(filteredNode)
}

STDOUT(result)