# pr5.gql
DataGraph loyalty = ACCESS("loyalty.n4j")
DataGraph output = loyalty

THROUGH (Node person : loyalty) {
  THROUGH (Node business : loyalty) {
    CONDIF (person{:TYPE i== "CustomerOf"}^business : loyalty) {
      THROUGH (Node otherPerson : loyalty) {
        CONDIF (person{:TYPE i== "Recommended"}^otherPerson : loyalty AND 
                otherPerson{:TYPE i== "CustomerOf"}^business : loyalty) {
          Association personCustomerOf = person.CALLASSOCIATION({:TYPE i== "CustomerOf"}^business : loyalty)
          Association otherPersonCustomerOf = otherPerson.CALLASSOCIATION({:TYPE i== "CustomerOf"}^business : loyalty)

          personCustomerOf.reward = personCustomerOf.reward ++ business.bonus
          otherPersonCustomerOf.reward = otherPersonCustomerOf.reward ++ business.bonus
          
          output.PLUS(personCustomerOf)
          output.PLUS(otherPersonCustomerOf)
        }
      }
    }
  }
}

output = output.NEGATE(:TYPE i== "Recommended")

STDOUT(output)