Graph graph = READFILE("tasks.n4j");
Graph result = graph; // This makes copy
FOR (Node nT : graph) {
  IF (-[priority >= 8]-> nT) { // nT is a target of some relationship with field priority with val >= 8
    FOR (Node nS : graph) {
      IF (nS -[available == True]->) {
        Relation rel;
        rel.:TYPE = "PossiblyAllocated";
        rel.:START_ID = nS;
        rel.:END_ID = nT;
        result.ADD(rel);
      }
    }
  }
}
PRINT (result);