DataStructure tasks = ACCESS("./tasks.n4j");
DataStructure tasksCopy = tasks;

tasks = tasks.CASE (
    dataPoint.HAS("priority") AND dataPoint.priority >= 8
);

THROUGH (DataPoint highPriorityTask : tasks) {
    THROUGH (DataPoint availableTask : tasks) {
        CONDIF (availableTask.HAS("available") AND availableTask.available i== True) {
            Association possiblyAllocated;
            possiblyAllocated.:CLASS = "PossiblyAllocated";
            possiblyAllocated.:START_ID = availableTask;
            possiblyAllocated.:END_ID = highPriorityTask;
            tasksCopy.PLUS(possiblyAllocated);
        }
    }
}

STDOUT (tasksCopy);