Gr gr = ACCESS 'tasks.n4j';

Gr out = gr.FIND(relationship -> 
    relationship.:TYPE == 'ToComplete' && relationship.priority >= 8
);

Gr new_nodes = out.FIND(node -> 
    node.:LABEL == 'Staff' && 
    node - [:TYPE == 'CanDo' && available == true] -> _
);

LOOPF (Gr n : new_nodes) {
    out = n - [:TYPE = 'PossiblyAllocated'] -> out;
}

out = gr.ARITH(
    :ID = :ID,
    site = site,
    :LABEL = :LABEL,
    
    description = description,
    duration = duration,
    
    name = name,
    
    priority = priority,
    :TYPE = :TYPE,
    
    available = available
);

OUT(out);