# pr3.gql
DataGraph table = ACCESS("./input/table.n4j")
DataGraph output

THROUGH (Node nodef1 : table) {
  THROUGH (Node nodef2 : table) {
    THROUGH (Node nodef3 : table) { 
      CONDIF (
        nodef1.points !== null AND nodef1.points i== nodef3.points AND
          ( nodef3{:TYPE i== "DrewWith"}^nodef2 AND nodef2{:TYPE i== "Beat"}^nodef1 OR
            nodef2{:TYPE i== "DrewWith"}^nodef3 AND nodef2{:TYPE i== "Beat"}^nodef1)
            ) {
        output.PLUS(nodef1)
      }
    }
  }
}

STDOUT (output)