DataGraph graph = ACCESS("table.n4j")
DataGraph result

THROUGH (Node n : graph) {
  THROUGH (Node n2 : graph) {
    THROUGH (Node n3 : graph) { 
      CONDIF (n.points !== null AND
          n.points i== n3.points AND
          ( n3{:TYPE i== "DrewWith"}^n2 AND n2{:TYPE i== "Beat"}^n OR
            n2{:TYPE i== "DrewWith"}^n3 AND n2{:TYPE i== "Beat"}^n)) {
        result.PLUS(n)
      }
    }
  }
}

STDOUT (result)