Graph graph = READFILE("networks.n4j");
Graph initial = graph.MATCH(firstname == r"^(A|B|C)");
Graph second;
FOR (Relation isFriendRelation : initial.GETRELATION(:TYPE == "IsFriend")) {
  IF (((initial.MATCH(:ID == isFriendRelation.:START_ID).age) < (initial.MATCH(:ID == isFriendRelation.:END_ID).age))) { // Check if Friend is older than themselves
    IF (initial.GETNODE(initial.GETRELATION(:TYPE == "WorksFor").MATCH(:START_ID == isFriendRelation.:END_ID).:END_ID).:LABEL.CONTAINS("Cafe")) { // Check if friend works in cafe
      second.ADD(initial.GETNODE(isFriendRelation.:START_ID));
      second.ADD(isFriendRelation);
    }
  }
}
PRINT(second);