DataStructure network = ACCESS("./network.n4j");
DataStructure output;

THROUGH (DataPoint person : network) {
    CONDIF (
        person.HAS("firstName") AND
        (
            person.firstName >= "A" AND person.firstName <= "C"
        )
    ) {
        output.PLUS(person);
        
        THROUGH (DataPoint friend : person.CALLASSOCIATION(association -[:TYPE i== "IsFriend"]>> dataPoint)) {
            CONDIF (
                friend.HAS("age") AND
                person.HAS("age") AND
                friend.age > person.age
            ) {
                DataStructure friendEmployers = friend.CALLASSOCIATION(association -[:TYPE i== "WorksFor"]>> dataPoint);
                Bool friendWorksInCafe = False;
                
                THROUGH (DataPoint employer : friendEmployers) {
                    CONDIF (employer.HAS("LABEL") AND employer.:LABEL i== "Cafe") {
                        friendWorksInCafe = True;
                    }
                }
                
                CONDIF (friendWorksInCafe i== False) {
                    output.PLUS(friend);
                    output.PLUS(person -[association.:TYPE i== "IsFriend"]>> friend);
                }
            }
        }
    }
}

STDOUT(output);