DataStructure loyalty = ACCESS("./loyalty.n4j");
DataStructure output = loyalty;

THROUGH (DataPoint p : loyalty) {
    THROUGH (DataPoint b : p.CALLDATAPOINT(dataPoint -[association.:CLASS i== "CustomerOf"]>> anyNode)) {
        DataStructure recommendedCustomers = p.CALLDATAPOINT(dataPoint -[association.:CLASS i== "Recommended"]>> anyNode);
        THROUGH (DataPoint q : recommendedCustomers.CALLDATAPOINT(dataPoint -[association.:CLASS i== "CustomerOf"]>> b)) {
            DataStructure pCustomerOf = p.CALLASSOCIATION(association -[:CLASS i== "CustomerOf"]>> b);
            DataStructure qCustomerOf = q.CALLASSOCIATION(association -[:CLASS i== "CustomerOf"]>> b);
            
            pCustomerOf.reward =+ b.bonus;
            qCustomerOf.reward =+ b.bonus;
        }
    }
}

output = output.CALLASSOCIATION(association -[:CLASS !== "Recommended"]>> dataPoint);

STDOUT (output);