DataGraph loyalty = ACCESS("loyalty.n4j")

THROUGH (Node nodef1 : loyalty) {
  THROUGH (Node nodef2 : loyalty) {
    THROUGH (Node nodef3 : loyalty) {
      CONDIF (nodef1 {:TYPE i== "CustomerOf"}^ nodef3) {
        CONDIF ((nodef1 {:TYPE i== "CustomerOf"}^ nodef2) AND (nodef2 {:TYPE i== "CustomerOf"}^ nodef3)) {
          loyalty.CALLASSOCIATION(:TYPE i== "CustomerOf").CASE(:START_ID i== nodef1 AND :END_ID i== nodef3).reward ++ nodef3.bonus
          loyalty.CALLASSOCIATION(:TYPE i== "CustomerOf").CASE(:START_ID i== nodef2 AND :END_ID i== nodef3).reward ++ nodef3.bonus
        }
      }
    }
  }
}

loyalty.NEGATE(loyalty.CALLASSOCIATION(:TYPE i== "Recommended"))
STDOUT(loyalty)